/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motosymotos.view;

import com.mycompany.motosymotos.controller.Controller_empleado;
import com.mycompany.motosymotos.controller.Controller_producto;
import com.mycompany.motosymotos.controller.Controller_screen;
import com.mycompany.motosymotos.controller.Controller_venta_producto;
import com.mycompany.motosymotos.controller.Controller_venta_producto_has_producto;
import com.mycompany.motosymotos.model.Empleado;
import com.mycompany.motosymotos.model.Producto;
import com.mycompany.motosymotos.model.Venta_producto;
import com.mycompany.motosymotos.model.Venta_producto_has_producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nelson Alvarez
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        cargar_modelo_empleado();
        cargar_modelo_producto();
        cargar_modelo_venta_producto();
        cargar_modelo_many_ventas();
    }

    //functions 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_doc_empleado = new javax.swing.JTextField();
        txt_email_empleado = new javax.swing.JTextField();
        txt_nombres_empleado = new javax.swing.JTextField();
        txt_telefono_empleado = new javax.swing.JTextField();
        txt_apellidos_empleado = new javax.swing.JTextField();
        txt_direccion_empleado = new javax.swing.JTextField();
        txt_f_nacimiento_empleado = new javax.swing.JTextField();
        txt_porcentaje_empleado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_agregar_empleado = new javax.swing.JButton();
        btn_actualizar_empleado = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btn_exit_empleado = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txt_eps_empleado = new javax.swing.JTextField();
        txt_fondo_pension_empleado = new javax.swing.JTextField();
        txt_arl_empleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_empleado = new javax.swing.JTable();
        btn_cancelar_empleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_ubc_bodega_producto = new javax.swing.JTextField();
        txt_precio_venta_producto = new javax.swing.JTextField();
        txt_precio_compra_producto = new javax.swing.JTextField();
        txt_ex_disponibles_producto = new javax.swing.JTextField();
        txt_nombre_producto = new javax.swing.JTextField();
        txt_marca_producto = new javax.swing.JTextField();
        txt_inv_minimo_producto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_agregar_producto = new javax.swing.JButton();
        btn_actualizar_producto = new javax.swing.JButton();
        btn_eliminar_producto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_producto = new javax.swing.JTable();
        txt_id_producto = new javax.swing.JTextField();
        btn_salir_producto = new javax.swing.JButton();
        btn_cancelar_producto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_id_venta_producto = new javax.swing.JTextField();
        txt_c_empleado_venta = new javax.swing.JTextField();
        txt_f_venta = new javax.swing.JTextField();
        txt_c_cliente_venta = new javax.swing.JTextField();
        txt_valor_venta = new javax.swing.JTextField();
        txt_venta_producto_id = new javax.swing.JTextField();
        txt_producto_venta = new javax.swing.JTextField();
        txt_cantidad_producto_venta = new javax.swing.JTextField();
        btn_salir_ventas = new javax.swing.JButton();
        btn_add_produc_venta = new javax.swing.JButton();
        btn_eliminar_produc_venta = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btn_actualizar_produc_venta1 = new javax.swing.JButton();
        btn_registrar_venta = new javax.swing.JButton();
        btn_eliminar_venta = new javax.swing.JButton();
        btn_actualizar_venta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_venta_producto = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_many_ventas = new javax.swing.JTable();
        btn_cancelar_venta = new javax.swing.JButton();

        jLabel9.setText("Porcentaje de pago");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txt_doc_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_doc_empleadoActionPerformed(evt);
            }
        });

        jLabel1.setText("C.C. Empleado");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Telefono");

        jLabel5.setText("Dirección");

        jLabel6.setText("Fecha de nacimiento");

        jLabel7.setText("Email");

        jLabel8.setText("Porcentaje de pago");

        jLabel10.setText("EPS");

        jLabel11.setText("Fondo de pensión");

        jLabel12.setText("ARL");

        btn_agregar_empleado.setBackground(new java.awt.Color(0, 102, 0));
        btn_agregar_empleado.setForeground(new java.awt.Color(0, 0, 0));
        btn_agregar_empleado.setText("Agregar");
        btn_agregar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_empleadoActionPerformed(evt);
            }
        });

        btn_actualizar_empleado.setBackground(new java.awt.Color(0, 0, 255));
        btn_actualizar_empleado.setForeground(new java.awt.Color(0, 0, 0));
        btn_actualizar_empleado.setText("Actualizar");
        btn_actualizar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_empleadoActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 0, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("EMPLEADOS");

        btn_exit_empleado.setText("Exit");
        btn_exit_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exit_empleadoActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(255, 0, 0));
        btn_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        tbl_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_empleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_empleado);

        btn_cancelar_empleado.setBackground(new java.awt.Color(255, 102, 0));
        btn_cancelar_empleado.setForeground(new java.awt.Color(0, 0, 0));
        btn_cancelar_empleado.setText("Cancelar");
        btn_cancelar_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_empleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_direccion_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_apellidos_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_telefono_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addComponent(txt_doc_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nombres_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(txt_f_nacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_email_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_porcentaje_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_eps_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_arl_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_agregar_empleado)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_fondo_pension_empleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_actualizar_empleado)
                                                .addGap(84, 84, 84)))))
                                .addGap(58, 58, 58)
                                .addComponent(btn_exit_empleado)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btn_eliminar)
                                .addGap(160, 160, 160)
                                .addComponent(btn_cancelar_empleado)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_doc_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nombres_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_apellidos_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_telefono_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_direccion_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_f_nacimiento_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(2, 2, 2)
                                .addComponent(btn_eliminar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_email_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_porcentaje_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_eps_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_fondo_pension_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_arl_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_cancelar_empleado)
                                        .addComponent(btn_actualizar_empleado))
                                    .addComponent(btn_agregar_empleado))
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_exit_empleado)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Empleados", jPanel1);

        jLabel14.setText("Nombre");

        jLabel15.setText("Inventario Mínimo");

        jLabel16.setText("Marca");

        jLabel17.setText("Precio Venta");

        jLabel18.setText("Precio Compra");

        jLabel19.setText("Existencias Disponibles");

        jLabel20.setText("Ubicación en Bodega");

        jLabel21.setText("PRODUCTOS");

        btn_agregar_producto.setBackground(new java.awt.Color(0, 153, 0));
        btn_agregar_producto.setForeground(new java.awt.Color(0, 0, 0));
        btn_agregar_producto.setText("Agregar");
        btn_agregar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_productoActionPerformed(evt);
            }
        });

        btn_actualizar_producto.setBackground(new java.awt.Color(0, 0, 255));
        btn_actualizar_producto.setForeground(new java.awt.Color(0, 0, 0));
        btn_actualizar_producto.setText("Actualizar");
        btn_actualizar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_productoActionPerformed(evt);
            }
        });

        btn_eliminar_producto.setBackground(new java.awt.Color(255, 0, 0));
        btn_eliminar_producto.setForeground(new java.awt.Color(0, 0, 0));
        btn_eliminar_producto.setText("Eliminar");
        btn_eliminar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_productoActionPerformed(evt);
            }
        });

        tbl_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_producto);

        btn_salir_producto.setText("Exit");
        btn_salir_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_productoActionPerformed(evt);
            }
        });

        btn_cancelar_producto.setBackground(new java.awt.Color(255, 102, 0));
        btn_cancelar_producto.setForeground(new java.awt.Color(0, 0, 0));
        btn_cancelar_producto.setText("Cancelar");
        btn_cancelar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_productoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_precio_compra_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_marca_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_precio_venta_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_agregar_producto)
                        .addGap(44, 44, 44)
                        .addComponent(btn_actualizar_producto)
                        .addGap(60, 60, 60)
                        .addComponent(btn_eliminar_producto)
                        .addGap(44, 44, 44)
                        .addComponent(btn_cancelar_producto)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_ex_disponibles_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_inv_minimo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(txt_ubc_bodega_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(201, 201, 201)
                        .addComponent(btn_salir_producto))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21))
                            .addComponent(btn_salir_producto))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txt_ex_disponibles_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txt_inv_minimo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ubc_bodega_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_actualizar_producto)
                            .addComponent(btn_eliminar_producto)
                            .addComponent(btn_cancelar_producto)
                            .addComponent(btn_agregar_producto))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_marca_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precio_venta_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precio_compra_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txt_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prodcutos", jPanel2);

        txt_venta_producto_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_venta_producto_idActionPerformed(evt);
            }
        });

        btn_salir_ventas.setText("Exit");
        btn_salir_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_ventasActionPerformed(evt);
            }
        });

        btn_add_produc_venta.setBackground(new java.awt.Color(153, 0, 204));
        btn_add_produc_venta.setForeground(new java.awt.Color(0, 0, 0));
        btn_add_produc_venta.setText("Añadir");
        btn_add_produc_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_produc_ventaActionPerformed(evt);
            }
        });

        btn_eliminar_produc_venta.setBackground(new java.awt.Color(153, 0, 204));
        btn_eliminar_produc_venta.setForeground(new java.awt.Color(0, 0, 0));
        btn_eliminar_produc_venta.setText("Eliminar");
        btn_eliminar_produc_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_produc_ventaActionPerformed(evt);
            }
        });

        jLabel22.setText("C.C. Empleado");

        jLabel23.setText("C.C. Cliente");

        jLabel24.setText("Fecha Venta [yyyy-mm-dd]");

        jLabel25.setText("Valor Venta");

        jLabel26.setBackground(new java.awt.Color(0, 0, 204));
        jLabel26.setText("VENTA PRODUCTO");

        jLabel27.setText("Cantidad Producto");

        jLabel28.setText("Id Producto");

        jLabel29.setText("Id Venta Producto");

        btn_actualizar_produc_venta1.setBackground(new java.awt.Color(153, 0, 204));
        btn_actualizar_produc_venta1.setForeground(new java.awt.Color(0, 0, 0));
        btn_actualizar_produc_venta1.setText("Actualizar");
        btn_actualizar_produc_venta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_produc_venta1ActionPerformed(evt);
            }
        });

        btn_registrar_venta.setBackground(new java.awt.Color(0, 255, 255));
        btn_registrar_venta.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrar_venta.setText("Registrar");
        btn_registrar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar_ventaActionPerformed(evt);
            }
        });

        btn_eliminar_venta.setBackground(new java.awt.Color(0, 255, 255));
        btn_eliminar_venta.setForeground(new java.awt.Color(0, 0, 0));
        btn_eliminar_venta.setText("Eliminar");
        btn_eliminar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_ventaActionPerformed(evt);
            }
        });

        btn_actualizar_venta.setBackground(new java.awt.Color(0, 204, 204));
        btn_actualizar_venta.setForeground(new java.awt.Color(0, 0, 0));
        btn_actualizar_venta.setText("Actualizar");
        btn_actualizar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_ventaActionPerformed(evt);
            }
        });

        tbl_venta_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_venta_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_venta_productoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_venta_producto);

        tbl_many_ventas.setForeground(new java.awt.Color(0, 0, 0));
        tbl_many_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_many_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_many_ventasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_many_ventas);

        btn_cancelar_venta.setText("Cancelar");
        btn_cancelar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_ventaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_valor_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_f_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_c_cliente_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_c_empleado_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(txt_id_venta_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301)
                        .addComponent(btn_cancelar_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_salir_ventas))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_actualizar_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_eliminar_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_registrar_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel26)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(txt_venta_producto_id, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_add_produc_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(txt_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_cantidad_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_eliminar_produc_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_actualizar_produc_venta1))))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_c_empleado_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_c_cliente_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_f_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_valor_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txt_id_venta_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btn_registrar_venta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_eliminar_venta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_actualizar_venta))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_venta_producto_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel29)
                                        .addComponent(btn_add_produc_venta)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_salir_ventas)
                                    .addComponent(btn_cancelar_venta)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_eliminar_produc_venta)
                                .addComponent(jLabel28))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_cantidad_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27)
                                .addComponent(btn_actualizar_produc_venta1)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas [Producto]", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exit_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exit_empleadoActionPerformed
        Controller_screen.cerrar_pantalla();
    }//GEN-LAST:event_btn_exit_empleadoActionPerformed

    private void txt_doc_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_doc_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_doc_empleadoActionPerformed
    //GUARDAR
    private void btn_agregar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_empleadoActionPerformed
        int doc_empleado = Integer.parseInt(txt_doc_empleado.getText());
        String nombres = txt_nombres_empleado.getText();
        String apellidos = txt_apellidos_empleado.getText();
        String telefono = txt_telefono_empleado.getText();
        String direcion = txt_direccion_empleado.getText();
        String f_nacimiento = txt_f_nacimiento_empleado.getText();
        String email = txt_email_empleado.getText();
        String porcent_pago = txt_porcentaje_empleado.getText();
        String eps = txt_eps_empleado.getText();
        String fondo_pension = txt_fondo_pension_empleado.getText();
        String arl = txt_arl_empleado.getText();

        Empleado emp = new Empleado(doc_empleado, nombres, apellidos, telefono, direcion, f_nacimiento, email, porcent_pago, eps, fondo_pension, arl);
        Controller_empleado.guardar_empleado(emp);
        limpiar_espacios_empleado();

        Controller_empleado.cargar_empleados(tbl_empleado, modelo_empleado);
    }//GEN-LAST:event_btn_agregar_empleadoActionPerformed

    private void btn_actualizar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_empleadoActionPerformed
        int doc_empleado = Integer.parseInt(txt_doc_empleado.getText());
        String nombres = txt_nombres_empleado.getText();
        String apellidos = txt_apellidos_empleado.getText();
        String telefono = txt_telefono_empleado.getText();
        String direcion = txt_direccion_empleado.getText();
        String f_nacimiento = txt_f_nacimiento_empleado.getText();
        String email = txt_email_empleado.getText();
        String porcent_pago = txt_porcentaje_empleado.getText();
        String eps = txt_eps_empleado.getText();
        String fondo_pension = txt_fondo_pension_empleado.getText();
        String arl = txt_arl_empleado.getText();

        Empleado emp = new Empleado(doc_empleado, nombres, apellidos, telefono, direcion, f_nacimiento, email, porcent_pago, eps, fondo_pension, arl);
        Controller_empleado.actualizar_empleado(emp);
        limpiar_espacios_empleado();

        Controller_empleado.cargar_empleados(tbl_empleado, modelo_empleado);
        txt_doc_empleado.setEnabled(true);
    }//GEN-LAST:event_btn_actualizar_empleadoActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el Documento del empleado a eliminar: "));
        Controller_empleado.eliminar_empleado(id, tbl_empleado, modelo_empleado);
        Controller_empleado.cargar_empleados(tbl_empleado, modelo_empleado);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void tbl_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_empleadoMouseClicked
        cargar_editar_empelado();
    }//GEN-LAST:event_tbl_empleadoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Controller_empleado.cargar_empleados(tbl_empleado, modelo_empleado);
        Controller_producto.cargar_producto(tbl_producto, modelo_producto);
        Controller_venta_producto.cargar_venta_producto(tbl_venta_producto, modelo_venta_producto);
        Controller_venta_producto_has_producto.cargar_venta_producto_has_producto(tbl_many_ventas, modelo_many_ventas);
        txt_id_producto.setVisible(false);
        txt_id_venta_producto.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btn_agregar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_productoActionPerformed
        String nombre = txt_nombre_producto.getText();
        String marca = txt_marca_producto.getText();
        double p_venta = Double.parseDouble(txt_precio_venta_producto.getText());
        double p_compra = Double.parseDouble(txt_precio_compra_producto.getText());
        int ex_dis = Integer.parseInt(txt_ex_disponibles_producto.getText());
        int inv_mini = Integer.parseInt(txt_inv_minimo_producto.getText());
        String ub_bode = txt_ubc_bodega_producto.getText();

        Producto pdt = new Producto(nombre, marca, p_venta, p_compra, ex_dis, inv_mini, ub_bode);
        Controller_producto.agregar_producto(pdt);
        limpiar_espacios_producto();

        Controller_producto.cargar_producto(tbl_producto, modelo_producto);
    }//GEN-LAST:event_btn_agregar_productoActionPerformed

    private void btn_actualizar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_productoActionPerformed
        int id = Integer.parseInt(txt_id_producto.getText());
        String nombre = txt_nombre_producto.getText();
        String marca = txt_marca_producto.getText();
        double p_venta = Double.parseDouble(txt_precio_venta_producto.getText());
        double p_compra = Double.parseDouble(txt_precio_compra_producto.getText());
        int ex_dis = Integer.parseInt(txt_ex_disponibles_producto.getText());
        int inv_mini = Integer.parseInt(txt_inv_minimo_producto.getText());
        String ub_bode = txt_ubc_bodega_producto.getText();

        Producto pdt = new Producto(id, nombre, marca, p_venta, p_compra, ex_dis, inv_mini, ub_bode);
        Controller_producto.actualizar_producto(pdt);
        limpiar_espacios_producto();

        Controller_producto.cargar_producto(tbl_producto, modelo_producto);
    }//GEN-LAST:event_btn_actualizar_productoActionPerformed

    private void btn_eliminar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_productoActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el id del product a eliminar: "));
        Controller_producto.eliminar_producto(id, tbl_producto, modelo_producto);
        Controller_producto.cargar_producto(tbl_producto, modelo_producto);
    }//GEN-LAST:event_btn_eliminar_productoActionPerformed

    private void tbl_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productoMouseClicked
        cargar_editar_producto();
    }//GEN-LAST:event_tbl_productoMouseClicked

    private void btn_salir_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_productoActionPerformed
        Controller_screen.cerrar_pantalla();
    }//GEN-LAST:event_btn_salir_productoActionPerformed

    private void btn_salir_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_ventasActionPerformed
        Controller_screen.cerrar_pantalla();
    }//GEN-LAST:event_btn_salir_ventasActionPerformed

    private void btn_registrar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar_ventaActionPerformed
        int doc_empleado = Integer.parseInt(txt_c_empleado_venta.getText());
        int id_cliente = Integer.parseInt(txt_c_cliente_venta.getText());
        String f_venta = txt_f_venta.getText();
        double valor_venta = Double.parseDouble(txt_valor_venta.getText());
        Venta_producto vp = new Venta_producto(doc_empleado, id_cliente, f_venta, valor_venta);
        Controller_venta_producto.agregar_venta_producto(vp);
        limpiar_espacios_venta();

        Controller_venta_producto.cargar_venta_producto(tbl_venta_producto, modelo_venta_producto);
    }//GEN-LAST:event_btn_registrar_ventaActionPerformed

    private void tbl_venta_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_venta_productoMouseClicked
        cargar_editar_venta_producto();
    }//GEN-LAST:event_tbl_venta_productoMouseClicked

    private void btn_eliminar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_ventaActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el id de la venta a eliminar: "));
        Controller_venta_producto.eliminar_venta_producto(id, tbl_venta_producto, modelo_venta_producto);
        Controller_venta_producto.cargar_venta_producto(tbl_venta_producto, modelo_venta_producto);
        Controller_venta_producto_has_producto.cargar_venta_producto_has_producto(tbl_many_ventas, modelo_many_ventas);
    }//GEN-LAST:event_btn_eliminar_ventaActionPerformed

    private void btn_actualizar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_ventaActionPerformed
        int id = Integer.parseInt(txt_id_venta_producto.getText());
        int doc_empleado = Integer.parseInt(txt_c_empleado_venta.getText());
        int id_cliente = Integer.parseInt(txt_c_cliente_venta.getText());
        String f_venta = txt_f_venta.getText();
        double valor_venta = Double.parseDouble(txt_valor_venta.getText());
        Venta_producto vp = new Venta_producto(id, doc_empleado, id_cliente, f_venta, valor_venta);
        Controller_venta_producto.actualizar_venta_producto(vp);
        limpiar_espacios_venta();
        Controller_venta_producto.cargar_venta_producto(tbl_venta_producto, modelo_venta_producto);
        txt_valor_venta.setEnabled(true);
        txt_c_cliente_venta.setEditable(true);
        txt_c_empleado_venta.setEditable(true);
    }//GEN-LAST:event_btn_actualizar_ventaActionPerformed

    private void btn_add_produc_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_produc_ventaActionPerformed
        int id_venta = Integer.parseInt(txt_venta_producto_id.getText());
        int id_producto = Integer.parseInt(txt_producto_venta.getText());
        int cantidad = Integer.parseInt(txt_cantidad_producto_venta.getText());
        
        Venta_producto_has_producto vpdt = new Venta_producto_has_producto(id_venta,id_producto,cantidad);
        Controller_venta_producto_has_producto.agregar_venta_producto_has_producto(vpdt);
        limpiar_espacio_many_ventas();
        Controller_producto.cargar_producto(tbl_producto, modelo_producto);
        Controller_venta_producto_has_producto.cargar_venta_producto_has_producto(tbl_many_ventas, modelo_many_ventas);
        Controller_venta_producto.cargar_venta_producto(tbl_venta_producto, modelo_venta_producto);
    }//GEN-LAST:event_btn_add_produc_ventaActionPerformed

    private void txt_venta_producto_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_venta_producto_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_venta_producto_idActionPerformed

    private void btn_eliminar_produc_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_produc_ventaActionPerformed
        int id_venta = Integer.parseInt(JOptionPane.showInputDialog("Digite el id de la venta en la que se eleiminará el producto: "));
        int id_producto = Integer.parseInt(JOptionPane.showInputDialog("Digite el id del producto a eliminar: ")); 
        Controller_venta_producto_has_producto.eliminar_venta_producto_has_producto(id_venta, id_producto, tbl_many_ventas, modelo_many_ventas);
        Controller_venta_producto_has_producto.cargar_venta_producto_has_producto(tbl_many_ventas, modelo_many_ventas);
        Controller_venta_producto.cargar_venta_producto(tbl_venta_producto, modelo_venta_producto);
        Controller_producto.cargar_producto(tbl_producto, modelo_producto);
    }//GEN-LAST:event_btn_eliminar_produc_ventaActionPerformed

    private void btn_actualizar_produc_venta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_produc_venta1ActionPerformed
        int id_venta = Integer.parseInt(txt_venta_producto_id.getText());
        int id_producto = Integer.parseInt(txt_producto_venta.getText());
        int cantidad = Integer.parseInt(txt_cantidad_producto_venta.getText());
        
        Venta_producto_has_producto vpdt = new Venta_producto_has_producto(id_venta,id_producto,cantidad);
        Controller_venta_producto_has_producto.actualizar_venta_producto_has_producto(vpdt);
        limpiar_espacio_many_ventas();
        txt_venta_producto_id.setText("");
        txt_venta_producto_id.setEnabled(true);
        txt_producto_venta.setEnabled(true);
        Controller_producto.cargar_producto(tbl_producto, modelo_producto);
        Controller_venta_producto.cargar_venta_producto(tbl_venta_producto, modelo_venta_producto);
        Controller_venta_producto_has_producto.cargar_venta_producto_has_producto(tbl_many_ventas, modelo_many_ventas);
    }//GEN-LAST:event_btn_actualizar_produc_venta1ActionPerformed

    private void tbl_many_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_many_ventasMouseClicked
        cargar_editar_many_ventas();
    }//GEN-LAST:event_tbl_many_ventasMouseClicked

    private void btn_cancelar_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_empleadoActionPerformed
        limpiar_espacios_empleado();
        txt_doc_empleado.setEnabled(true);
    }//GEN-LAST:event_btn_cancelar_empleadoActionPerformed

    private void btn_cancelar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_productoActionPerformed
        limpiar_espacios_producto();
    }//GEN-LAST:event_btn_cancelar_productoActionPerformed

    private void btn_cancelar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_ventaActionPerformed
        limpiar_espacio_many_ventas();
        limpiar_espacios_venta();
        txt_c_cliente_venta.setEnabled(true);
        txt_c_empleado_venta.setEnabled(true);
        txt_valor_venta.setEnabled(true);
        txt_venta_producto_id.setEnabled(true);
        txt_producto_venta.setEnabled(true);
        
    }//GEN-LAST:event_btn_cancelar_ventaActionPerformed

    //funtions
    private void limpiar_espacios_empleado() {
        String t = "";
        txt_doc_empleado.setText(t);
        txt_nombres_empleado.setText(t);
        txt_apellidos_empleado.setText(t);
        txt_direccion_empleado.setText(t);
        txt_email_empleado.setText(t);
        txt_f_nacimiento_empleado.setText(t);
        txt_porcentaje_empleado.setText(t);
        txt_telefono_empleado.setText(t);
        txt_eps_empleado.setText(t);
        txt_fondo_pension_empleado.setText(t);
        txt_arl_empleado.setText(t);

    }

    private void limpiar_espacios_producto() {
        String t = "";
        txt_nombre_producto.setText(t);
        txt_marca_producto.setText(t);
        txt_precio_compra_producto.setText(t);
        txt_precio_venta_producto.setText(t);
        txt_ex_disponibles_producto.setText(t);
        txt_inv_minimo_producto.setText(t);
        txt_ubc_bodega_producto.setText(t);
    }

    private void limpiar_espacios_venta() {
        String t = "";
        txt_c_cliente_venta.setText(t);
        txt_c_empleado_venta.setText(t);
        txt_f_venta.setText(t);
        txt_valor_venta.setText(t);
    }

    private void limpiar_espacio_many_ventas() {
        String t = "";
        //txt_venta_producto_id.setText(t);
        txt_producto_venta.setText(t);
        txt_cantidad_producto_venta.setText(t);
    }
    //table
    DefaultTableModel modelo_empleado = new DefaultTableModel();

    private void cargar_modelo_empleado() {
        modelo_empleado.addColumn("Documento");
        modelo_empleado.addColumn("Nombres");
        modelo_empleado.addColumn("Apellidos");
        modelo_empleado.addColumn("Telefono");
        modelo_empleado.addColumn("Dirección");
        modelo_empleado.addColumn("Fecha nacimiento");
        modelo_empleado.addColumn("Email");
        modelo_empleado.addColumn("Porcentaje Pago");
        modelo_empleado.addColumn("EPS");
        modelo_empleado.addColumn("Fondo Pensión");
        modelo_empleado.addColumn("ARL");

        tbl_empleado.setModel(modelo_empleado);
    }
    DefaultTableModel modelo_producto = new DefaultTableModel();

    private void cargar_modelo_producto() {
        modelo_producto.addColumn("Id Producto");
        modelo_producto.addColumn("Nombre");
        modelo_producto.addColumn("Marca");
        modelo_producto.addColumn("Precio Venta");
        modelo_producto.addColumn("Precio Compra");
        modelo_producto.addColumn("existencias Disponibles");
        modelo_producto.addColumn("Inventario Minimo");
        modelo_producto.addColumn("Ubicación Bodega");
        tbl_producto.setModel(modelo_producto);
    }
    DefaultTableModel modelo_venta_producto = new DefaultTableModel();

    private void cargar_modelo_venta_producto() {
        modelo_venta_producto.addColumn("Id venta producto");
        modelo_venta_producto.addColumn("CC Empleado");
        modelo_venta_producto.addColumn("CC Cliente");
        modelo_venta_producto.addColumn("Fecha venta");
        modelo_venta_producto.addColumn("Valor Venta");
        tbl_venta_producto.setModel(modelo_venta_producto);
    }

    DefaultTableModel modelo_many_ventas = new DefaultTableModel();
    
    private void cargar_modelo_many_ventas(){
        modelo_many_ventas.addColumn("Id venta");
        modelo_many_ventas.addColumn("Id producto");
        modelo_many_ventas.addColumn("Cantidad producto");
        tbl_many_ventas.setModel(modelo_many_ventas);
    }

    

    //cargue sobre los edidtext
            
    private void cargar_editar_many_ventas() {
        int fila_select = tbl_many_ventas.getSelectedRow();
        if (fila_select >= 0) {
            txt_venta_producto_id.setText((tbl_many_ventas.getValueAt(fila_select, 0)).toString());
            txt_producto_venta.setText((tbl_many_ventas.getValueAt(fila_select, 1)).toString());
            txt_cantidad_producto_venta.setText((tbl_many_ventas.getValueAt(fila_select, 2)).toString());
        }
        txt_venta_producto_id.setEnabled(false);
        txt_producto_venta.setEnabled(false);
    }
    
    private void cargar_editar_venta_producto() {
        int fila_select = tbl_venta_producto.getSelectedRow();
        if (fila_select >= 0) {
            txt_id_venta_producto.setText((tbl_venta_producto.getValueAt(fila_select, 0)).toString());
            txt_c_cliente_venta.setText((tbl_venta_producto.getValueAt(fila_select, 2)).toString());
            txt_c_empleado_venta.setText((tbl_venta_producto.getValueAt(fila_select, 1)).toString());
            txt_f_venta.setText((tbl_venta_producto.getValueAt(fila_select, 3)).toString());
            txt_valor_venta.setText((tbl_venta_producto.getValueAt(fila_select, 4)).toString());
        }
        txt_valor_venta.setEnabled(false);
        txt_c_cliente_venta.setEditable(false);
        txt_c_empleado_venta.setEditable(false);
    }

    private void cargar_editar_empelado() {
        int fila_select = tbl_empleado.getSelectedRow();
        if (fila_select >= 0) {
            txt_doc_empleado.setText((tbl_empleado.getValueAt(fila_select, 0).toString()));
            txt_nombres_empleado.setText((tbl_empleado.getValueAt(fila_select, 1).toString()));
            txt_apellidos_empleado.setText((tbl_empleado.getValueAt(fila_select, 2).toString()));
            txt_direccion_empleado.setText((tbl_empleado.getValueAt(fila_select, 3).toString()));
            txt_email_empleado.setText((tbl_empleado.getValueAt(fila_select, 4).toString()));
            txt_f_nacimiento_empleado.setText((tbl_empleado.getValueAt(fila_select, 5).toString()));
            txt_porcentaje_empleado.setText((tbl_empleado.getValueAt(fila_select, 6).toString()));
            txt_telefono_empleado.setText((tbl_empleado.getValueAt(fila_select, 7).toString()));
            txt_eps_empleado.setText((tbl_empleado.getValueAt(fila_select, 8).toString()));
            txt_fondo_pension_empleado.setText((tbl_empleado.getValueAt(fila_select, 9).toString()));
            txt_arl_empleado.setText((tbl_empleado.getValueAt(fila_select, 10).toString()));
        }
        txt_doc_empleado.setEnabled(false);
    }

    private void cargar_editar_producto() {
        int fila_selct = tbl_producto.getSelectedRow();
        if (fila_selct >= 0) {
            txt_id_producto.setText((tbl_producto.getValueAt(fila_selct, 0)).toString());
            txt_nombre_producto.setText((tbl_producto.getValueAt(fila_selct, 1)).toString());
            txt_marca_producto.setText((tbl_producto.getValueAt(fila_selct, 2)).toString());
            txt_precio_compra_producto.setText((tbl_producto.getValueAt(fila_selct, 3)).toString());
            txt_precio_venta_producto.setText((tbl_producto.getValueAt(fila_selct, 4)).toString());
            txt_ex_disponibles_producto.setText((tbl_producto.getValueAt(fila_selct, 5)).toString());
            txt_inv_minimo_producto.setText((tbl_producto.getValueAt(fila_selct, 6)).toString());
            txt_ubc_bodega_producto.setText((tbl_producto.getValueAt(fila_selct, 7)).toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar_empleado;
    private javax.swing.JButton btn_actualizar_produc_venta1;
    private javax.swing.JButton btn_actualizar_producto;
    private javax.swing.JButton btn_actualizar_venta;
    private javax.swing.JButton btn_add_produc_venta;
    private javax.swing.JButton btn_agregar_empleado;
    private javax.swing.JButton btn_agregar_producto;
    private javax.swing.JButton btn_cancelar_empleado;
    private javax.swing.JButton btn_cancelar_producto;
    private javax.swing.JButton btn_cancelar_venta;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_eliminar_produc_venta;
    private javax.swing.JButton btn_eliminar_producto;
    private javax.swing.JButton btn_eliminar_venta;
    private javax.swing.JButton btn_exit_empleado;
    private javax.swing.JButton btn_registrar_venta;
    private javax.swing.JButton btn_salir_producto;
    private javax.swing.JButton btn_salir_ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_empleado;
    private javax.swing.JTable tbl_many_ventas;
    private javax.swing.JTable tbl_producto;
    private javax.swing.JTable tbl_venta_producto;
    private javax.swing.JTextField txt_apellidos_empleado;
    private javax.swing.JTextField txt_arl_empleado;
    private javax.swing.JTextField txt_c_cliente_venta;
    private javax.swing.JTextField txt_c_empleado_venta;
    private javax.swing.JTextField txt_cantidad_producto_venta;
    private javax.swing.JTextField txt_direccion_empleado;
    private javax.swing.JTextField txt_doc_empleado;
    private javax.swing.JTextField txt_email_empleado;
    private javax.swing.JTextField txt_eps_empleado;
    private javax.swing.JTextField txt_ex_disponibles_producto;
    private javax.swing.JTextField txt_f_nacimiento_empleado;
    private javax.swing.JTextField txt_f_venta;
    private javax.swing.JTextField txt_fondo_pension_empleado;
    private javax.swing.JTextField txt_id_producto;
    private javax.swing.JTextField txt_id_venta_producto;
    private javax.swing.JTextField txt_inv_minimo_producto;
    private javax.swing.JTextField txt_marca_producto;
    private javax.swing.JTextField txt_nombre_producto;
    private javax.swing.JTextField txt_nombres_empleado;
    private javax.swing.JTextField txt_porcentaje_empleado;
    private javax.swing.JTextField txt_precio_compra_producto;
    private javax.swing.JTextField txt_precio_venta_producto;
    private javax.swing.JTextField txt_producto_venta;
    private javax.swing.JTextField txt_telefono_empleado;
    private javax.swing.JTextField txt_ubc_bodega_producto;
    private javax.swing.JTextField txt_valor_venta;
    private javax.swing.JTextField txt_venta_producto_id;
    // End of variables declaration//GEN-END:variables
}
